### ISSUE TITLE
forEach pattern fails hard if array is empty

### ISSUE THREAD

**Issue by OJFord** [chaoran/node-finish#2]
The [following pattern](http://stackoverflow.com/a/14588973/1446048) causes problems if `fooArray === []`:

```
finish(function(async){
    fooArray.forEach(function(foo){
        async(function(done){
            fooHandler(foo, done);
        });
    });
}, finished);
```

The rather cryptic error follows:

> TypeError: cannot read property 'kickoff' of undefined

I haven't looked at the code; don't have a PR, but I assume this isn't intended behaviour.

The callbacks are already quite deep here, seems a shame to wrap it in an `if(fooArray)`; especially when it is clearly expected that `forEach` handles the empty array fine.

**Comment by chaoran** [comment]
You're right it is not the intended behavior. You can expect a fix by the weekend. Thank you for reporting it.

**Comment by OJFord** [comment]
No problem - a pleasant surprise that you're still (and promptly) willing to support an otherwise ~stale~ stable project! ;)

**Comment by OJFord** [comment]
Any chance you could also bump the version number, for npm?

I quite likely will run it against an empty array sometimes (as in, the data will be that way) so it would be nice to specify, say `">=0.6.3"` in dependencies.

**Comment by chaoran** [comment]
See #24b552c

**Comment by OJFord** [comment]
Premature moan. Thanks!
